### ISSUE TITLE
Feature: User can Sign Up/In

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/react-native-aora#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up or sign in to an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user opens the app, they will see a splash screen that will go to the sign in/sign up page. Sign in/sign up page with have link to other option under button.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brandon-moy/react-native-aora/assets/109567499/c2f80e9d-fb42-4156-89dc-6736a60e8c04)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create appwrite database and create an appwrite.js file for config
- [x] Create a database with a users and videos collection
- [x] Assign title, thumbnail, prompt, video, and relationship to users as attributes to videos collection
- [x] Assign username, email, avatar, and accountid attributes to users collection
- [x] Create a storage bucket for files
- [x] create a config object connecting endpoint, platform, projectId, databaseId, userCollectionId,  videoCollectionId, and storageId
- [x] use react-native-appwrite sdk to create a new client using the endpoint, projectId, and platformId

### ⚡ Client Tasks

- [x] Create a component to have navigation tabs for bottom of application
- [x] Update component to display four icons for home, create, profile, and saved
- [x] Move to the splash page and set up a SafeAreaView
- [x] Add images, text, and flavor text to splash screen
- [x] Create a custom TouchableOpacity to be a button
- [x] Add StatusBar styles so make top area of phone cohesive with rest of application design
- [x] Create custom FormField component to be reusable for sign-in/sign-up forms
- [x] Utilize FormField to take email/password on Sign In page
- [x] Utilize CustomButton for submit
- [x] Add link to go between Sign In and Sign Up screen options
- [x] Use same page layout of Sign In for Sign Up but add a username field to form
--- go to database ---
- [x] Create createUser function, assign it with dummy values and add to sign-up onSubmit to test  connection
--- IF UNSUCCESSFUL CHECK CONNECTIONS AND VARIABLES ---
- [x] Build out actual createUser function
- [x] use try catch to create a new account, creating a new unique ID, and adding/using email, password, and username from props (will receive from submit)
- [x] check if new account was created else throw error
- [x] create a url with the username initials
- [x] create the new user in the document - needs dbid, ucid, id, accountid, email, username, and avatar
- [x] return the newUser
- [x] In sign-up.jsx update submit function
- [x] validate username, email, and password are all filled out
- [x] await creating the user
- [x] send user to home for time being
--- IF UNSUCCESSFUL FOLLOW ERRORS AND CHECK CONNECTIONS AND VARIABLES ---
- [x] Use same logic in sign-in.jsx
- [x] Remove instances of username when using in sign-in.jsx
- [x] Create GlobalContext to hold user session
- [x] Create a getCurrentUser function in appwrite.js to use in GlobalContext to determine if a user is already signed in
- [x] Utilize GlobalContext in layout, index, sign-in, and sign-up
- [x] layout - surround all Stacks with GlobalProvider
- [x] index - check if isLoading is false and if a use isLoggedIn and if so redirect to /home
- [x] sign-in and sign-up - in try catch assign result to user and setIsLoggedIn to true

### 🧑‍⚕️ Clean Up Tasks

- [x] Confirm consistent design and styling across screens
- [x] Remove all console logs.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural.
- [x] Create GIFs of the feature being used on both mobile for inclusion in Pull Request.
