### ISSUE TITLE
Feature: User can view the home page when authenticated

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/react-native-aora#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the home page when authenticated

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user is signed in, they are redirected to the home page which should display their username, navigation tabs, sections for videos (adding videos in future feature) and searching through videos (also future feature)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brandon-moy/react-native-aora/assets/109567499/8176a821-ab6d-4956-a67e-e086fd9047b7)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Create some videos in appwrite's dashboard directly (until create page is set up)
- [x] in appwrite.js...
- [x] export a new getAllPosts async function
- [ ] we should await the listDocuments from databases which needs
- [ ] databaseid
- [ ] videocollectionid
- [ ] return a posts.documents

### ⚡ Client Tasks

- [x] Wrap the Home page in a SafeAreaView and then create a FlatList element
- [x] Flatlist should have the following:
  - [x] data (hard code dummy data for now) 
  - [x]  keyExtractor (to get the item id)
  - [x] renderItem to render Text elements with id for now
  - [x] ListHeaderComponent
    - [x] Returns views with text for the Welcome Back and username (hard code for now)
- [x] Copy FormField into a SearchInput component (remember to change function name and export)
- [x] Remove outer View and title Text element
- [x] Replace title logic with a TouchableOpacity that has the icons.search icon for a magnifying glass
- [x] Add a SearchInput under the last View back in home.jsx
- [x] Add a View and Text element for the Latest Videos
- [x] Back in components, make a new Trending.jsx component which takes a posts prop and add it under the Latest Videos Text
- [x] Use another FlatList in Trending using posts for the data, a keyExtractor to get the item id, and render item to render the item id text for now
- [x] Add a horizontal prop to change the list direction
- [x] Add a ListEmptyComponent attribute that takes an arrow function that returns an empty text string for now
- [x] Create an EmptyState component that takes props of title and subtitle
  - [x] Import images to EmptyState to render the srouce of images.empty
  - [x] Add 2 text components, one that renders the title and one that renders the subtitle
  - [x] Render a CustomButton component that has
    - [x] title "Create video"
    - [x] handlePress callback function that calls router and pushes to "/create"
    - [x] containerStyles of full width and margin top and bottom of 5
- [x] Add a refreshControl to the FlatList in home.jsx
- [x] Return should be a RefreshControl component from react-native with refreshing and onRefresh properties
- [x] Create a refreshing and setRefreshing state snipper
- [x] create an onRefresh async function that sets refreshing to true, comment for future fetch, and set refreshing back to false
--- go to server tasks ---
- [x] Create a new useAppwrite custom hook in lib
- [x] create the useAppwrite function and pass the prop of a function (fn)
- [x] Create two new states for data, and isLoading
- [x] create a useEffect to load the data when the page initializes
- [x] create an async function (fetchData) then call the function inside the useEffect
- [x] This function should setIsLoading to true, try to call the function from props before finally setIsLoading to false
- [x] Create another function called refetch that just calls the fetchData function
- [x] return data, refetch, and isLoading from the useAppwrite function
- [ ] import useAppwrite in home and destructure data as posts and pass the getAllPosts function as a prop

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
