### ISSUE TITLE
Feature: User can sign out

### ISSUE THREAD

**Issue by brandon-moy** [brandon-moy/react-native-aora#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have a TouchableOpacity (button) on the profile page that will allow them to sign out of their account

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/brandon-moy/react-native-aora/assets/109567499/18adde24-afbd-4cd6-8c0e-8077c19c6fe0)

![image](https://github.com/brandon-moy/react-native-aora/assets/109567499/c038d2ac-4c86-4060-af6d-6ddd539c441b)

While wireframe is of entire profile page, this feature will only implement the sign out button

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Create a new async function in lib/appwrite.js for signOut
- [x] This function should delete the current session of the account and then return the session

### ⚡ Client Tasks

- [x] Add a TouchableOpacity to the profile screen in (tabs)/profile.jsx
- [x] Inside of the TouchableOpacity render an image with the icon
- [x] Create a function for logout that will be utilized in the TouchableOpacity's onPress attribute
- [x] Import the signOut function from appwrite.js to use in the logout function
- [x] useGlobalContext to get the setUser and setIsLoggedIn state functions
- [x] await the signOut call then setUser to null and setIsLoggedIn to false
- [x] replace the router string to "/sign-in"

### 🧑‍⚕️ Clean Up Tasks

- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
